name: dartz_plus_workspace

packages:
  - packages/*
  - example

scripts:
  test:
    description: Run tests in all packages.
    run: melos run test:flutter && melos run test:dart

  test:flutter:
    exec: flutter test
    packageFilters:
      dependsOn: flutter_test
      dirExists: test

  test:dart:
    exec: dart test
    packageFilters:
      noDependsOn: flutter_test
      dirExists: test

  analyze:
    exec: dart analyze .
    description: Run analysis in all packages.

  build:
    exec: dart run build_runner build -d
    description: Run build_runner in packages that depend on it.
    packageFilters:
      dependsOn: build_runner

  postbootstrap: dart pub get
